-- 문제: 자동차 평균 대여 기간 구하기
-- 유형: AGGREGATION / AVG / GROUP BY / HAVING / DATE FUNCTION
-- 핵심: 자동차별 대여 기간 평균을 계산하고 평균이 7일 이상인 차량 조회
-- 조건: 평균 대여 기간 >= 7
-- 정렬: 평균 대여 기간 DESC, CAR_ID DESC

SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
