-- 문제: 업그레이드 할 수 없는 아이템 구하기
-- 유형: JOIN / NOT IN / 서브쿼리
-- 핵심: 다른 아이템의 PARENT로 사용되지 않는 아이템 조회
-- 조건: ITEM_ID NOT IN (SELECT PARENT_ITEM_ID)
-- 정렬: ITEM_ID DESC

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
    ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY I.ITEM_ID DESC;
