-- 문제: ROOT 아이템 구하기
-- 유형: JOIN / NULL 조건
-- 핵심: PARENT_ITEM_ID가 NULL인 ROOT 아이템 조회
-- 조건: PARENT_ITEM_ID IS NULL
-- 정렬: ITEM_ID ASC

SELECT
    I.ITEM_ID,
    I.ITEM_NAME
FROM ITEM_INFO I
JOIN ITEM_TREE T
    ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID ASC;
