-- 문제: 연도별 대장균 크기의 편차 구하기
-- 유형: GROUP BY / MAX / JOIN / DATE 함수
-- 핵심: 연도별 최대 대장균 크기를 구한 뒤 각 개체와 비교하여 편차 계산
-- 조건: YEAR(MAX SIZE) - SIZE_OF_COLONY
-- 정렬: YEAR ASC, YEAR_DEV ASC

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC;
