-- 문제: 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- 유형: GROUP BY / HAVING / DATE 함수 / SUBQUERY
-- 핵심: 2022-08 ~ 2022-10 기간 동안 총 대여 횟수가 5회 이상인 자동차의 월별 대여 횟수 조회
-- 조건: 2022-08-01 ~ 2022-10-31
-- 정렬: MONTH ASC, CAR_ID DESC

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
