-- 문제: 저자 별 카테고리 별 매출액 집계하기
-- 유형: JOIN / SUM / GROUP BY / DATE 필터
-- 핵심: 2022년 1월 판매 데이터를 기준으로 저자와 카테고리별 매출 계산
-- 조건: SALES_DATE = 2022년 1월
-- 정렬: AUTHOR_ID ASC, CATEGORY DESC

SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID ASC,
    B.CATEGORY DESC;
