-- 문제: 5월 식품들의 총매출 조회하기
-- 유형: JOIN / SUM / GROUP BY / DATE 필터
-- 핵심: 2022년 5월 생산된 식품들의 총매출 계산
-- 조건: PRODUCE_DATE = 2022년 5월
-- 정렬: TOTAL_SALES DESC, PRODUCT_ID ASC

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * F.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER F
    ON P.PRODUCT_ID = F.PRODUCT_ID
WHERE F.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;
